### ISSUE TITLE
actions

### ISSUE THREAD

**Issue by vitaliybeinspired** [Naoki95957/Collect-Forecast-Visualize#60]
naoki I merged masters into vitaliy branch and it started to run the action checks. I tried to find and cancel everything running. should have just deleted mine and branched out from master to avoid using minutes.

**Comment by Naoki95957** [comment]
It's not a big deal and you've consumed 0 minutes. Master branch is the only one with all checks. 

All other branches get a raspberry pi for checks;
You'll notice the job in actions will all say 'python package' and if it's appended with '(self-hosted)' that means is the rpi.

**Comment by Naoki95957** [comment]
That said, idk that the rpi is even connected atm

**Comment by Naoki95957** [comment]
It's not running rn so it would've sat idle for a while.

I'll turn it back on tomorrow.

**Comment by vitaliybeinspired** [comment]
oh okay, nevermind then. Thought I used a lot of minutes since it showed lots of minutes.
